[discord] # all the configs for the discord part of the bot
token = "" # Put your token here
prefix = ":3" # the prefix that every command begins with
admin_role = ""
mod_role = ""

[database]
host="0.0.0.0"
db_name="owo_bot_db"
username="postgres"
password="" # make sure this is the same as in config/db-passwd.txt (this is for docker)